### ISSUE TITLE
404 pages contains invalid links

### ISSUE THREAD

**Issue by moul** [berty/www.berty.tech#31]
if you land on https://berty.tech/blog/lkjsdflkjsdf or https://berty.tech/blog/lkjsdflkjsdf/, you will get a 404 page -> normal :)

but if you click on a link in the menu, it will generate another 404 link -> problem

**Comment by fte378** [comment]
Caused by the generation of relative links. Not sure how to handle this.
Maybe a lambda function which does a redirect to a real page.

I used this once to get notified about missing css or javascript files.

**Comment by cdeleeuwe** [comment]
Thanks @fte378 . Yes, I think it's caused by the relative URLs. Similar as described here https://community.netlify.com/t/slash-breaks-relative-urls-in-404-page/10248

Basically the 404 page is generated with paths relative to the root, but Netlify serves the 404 file from different nested locations as well, such as /blog/sdfdwsm.

I think main reason we used relativeURLs was to host it on IPFS, but since we already have 2 different build commands for Netlify and IPFS, I see 3 possible options in order of preference (IMO):
1. Force absolute paths for URLs on the 404 page only, but not sure this is possible with Hugo.
2. Remove the relativeURLs from regular build command. 
3. Add post-build script that changes relative paths on 404 page

**Comment by cdeleeuwe** [comment]
Looks like option 1 works :) .. https://deploy-preview-91--bertytech.netlify.app/blog/dsdsdsfdfdggr
