### ISSUE TITLE
Add comparison to SimpleX chat

### ISSUE THREAD

**Issue by RageGamerBoi** [berty/www.berty.tech#357]
Add a comparison to https://simplex.chat/ in the FAQ section.

**Comment by LFGaming** [comment]
As stated in the [Compare page](https://berty.tech/compare) the Comparison list is not maintained much anymore because its to much effort and updates to often. This is not to say that it never will but maybe you can better understand why to use the Berty messenger when reading the [Compare page](https://berty.tech/compare).

> You can have a look at it, it is available [here ](https://berty.tech/faq#what-are-the-advantages-of-berty-compared-to-the-other-messengers)and you can even contribute to it. But to be honest, it’s particularly hard to be extensive, tricky to be objective, and awful to maintain.
